#!/bin/bash
#
# install.sh — Install Guezli/postfix-sasl-bf into a local Crowdsec instance.
# Auto-detects Mailcow's postfix container and adds an appropriate acquisition.
#
# Usage:
#   curl -fsSL https://raw.githubusercontent.com/Guezli/postfix-sasl-bf/main/install.sh | sudo bash
#   # or download first, inspect, then run:
#   curl -fsSL https://raw.githubusercontent.com/Guezli/postfix-sasl-bf/main/install.sh -o /tmp/install.sh
#   less /tmp/install.sh
#   sudo bash /tmp/install.sh
#
set -euo pipefail

REPO_RAW="https://raw.githubusercontent.com/Guezli/postfix-sasl-bf/main"
SCENARIO_DEST="/etc/crowdsec/scenarios/postfix-sasl-bf.yaml"
ACQUIS_DEST="/etc/crowdsec/acquis.d/postfix-sasl-bf.yaml"

color() { printf '\033[%sm%s\033[0m' "$1" "$2"; }
ok()    { echo "$(color '1;32' '✓') $*"; }
warn()  { echo "$(color '1;33' '!') $*"; }
fail()  { echo "$(color '1;31' '✗') $*" >&2; exit 1; }
info()  { echo "$(color '1;34' '→') $*"; }

[[ $EUID -eq 0 ]] || fail "Please run as root (or via sudo)."

# ── 1. Crowdsec installed? ─────────────────────────────────────────────
command -v cscli >/dev/null || fail "cscli not found — is Crowdsec installed on this host?"
ok "Crowdsec found ($(cscli version 2>&1 | grep -i 'version' | head -1 || true))"

mkdir -p /etc/crowdsec/scenarios /etc/crowdsec/acquis.d

# ── 2. Required parser/collection (crowdsecurity/postfix) ──────────────
if cscli collections list 2>/dev/null | grep -qE "crowdsecurity/postfix\b"; then
    ok "crowdsecurity/postfix collection already installed"
else
    info "Installing crowdsecurity/postfix collection (provides postfix-logs parser)..."
    cscli collections install crowdsecurity/postfix
    ok "Installed"
fi

# ── 3. Acquisition: detect postfix log source ──────────────────────────
EXISTING_ACQ=""
if grep -rEl 'mailcowdockerized-postfix-mailcow-1|/var/log/mail\.log|postfix' /etc/crowdsec/acquis.yaml /etc/crowdsec/acquis.d/ 2>/dev/null \
        | grep -v "$ACQUIS_DEST" | head -1 > /tmp/.acq-check; then
    EXISTING_ACQ=$(cat /tmp/.acq-check)
    rm -f /tmp/.acq-check
fi

if [[ -n "$EXISTING_ACQ" ]]; then
    ok "Existing postfix acquisition found in $EXISTING_ACQ — leaving it alone"
elif [[ -f "$ACQUIS_DEST" ]]; then
    ok "Acquisition $ACQUIS_DEST already exists — leaving it alone"
else
    POSTFIX_CONTAINER=""
    if command -v docker >/dev/null; then
        POSTFIX_CONTAINER=$(docker ps --format '{{.Names}}' 2>/dev/null \
            | grep -E 'postfix.*mailcow|mailcow.*postfix' | head -1 || true)
    fi
    if [[ -n "$POSTFIX_CONTAINER" ]]; then
        info "Detected Mailcow postfix container: $POSTFIX_CONTAINER"
        cat > "$ACQUIS_DEST" <<EOF
---
# Auto-generated by Guezli/postfix-sasl-bf install.sh
source: docker
container_name:
  - $POSTFIX_CONTAINER
labels:
  type: syslog
EOF
        ok "Wrote acquisition: $ACQUIS_DEST"
    elif [[ -f /var/log/mail.log ]]; then
        info "No Mailcow container, but /var/log/mail.log exists — using file source"
        cat > "$ACQUIS_DEST" <<EOF
---
# Auto-generated by Guezli/postfix-sasl-bf install.sh
source: file
filenames:
  - /var/log/mail.log
labels:
  type: syslog
EOF
        ok "Wrote acquisition: $ACQUIS_DEST"
    else
        warn "No postfix log source detected (no Mailcow container, no /var/log/mail.log)."
        warn "You'll need to add an acquisition manually — see README:"
        warn "  https://github.com/Guezli/postfix-sasl-bf#requirements"
    fi
fi

# ── 4. Install scenario ────────────────────────────────────────────────
info "Downloading scenario from $REPO_RAW/scenarios/postfix-sasl-bf.yaml"
curl -fsSL -o "${SCENARIO_DEST}.new" "$REPO_RAW/scenarios/postfix-sasl-bf.yaml"
if [[ -f "$SCENARIO_DEST" ]] && cmp -s "$SCENARIO_DEST" "${SCENARIO_DEST}.new"; then
    rm -f "${SCENARIO_DEST}.new"
    ok "Scenario already up-to-date"
else
    mv "${SCENARIO_DEST}.new" "$SCENARIO_DEST"
    chmod 644 "$SCENARIO_DEST"
    ok "Scenario installed: $SCENARIO_DEST"
fi

# ── 5. Reload Crowdsec ─────────────────────────────────────────────────
info "Reloading Crowdsec..."
if systemctl is-active --quiet crowdsec; then
    systemctl reload crowdsec
    sleep 2
    ok "Crowdsec reloaded"
else
    warn "Crowdsec service not active — start with: systemctl start crowdsec"
fi

# ── 6. Verify ──────────────────────────────────────────────────────────
if cscli scenarios list 2>/dev/null | grep -qE '\bGuezli/postfix-sasl-bf\b'; then
    ok "Scenario active: Guezli/postfix-sasl-bf"
else
    fail "Scenario not loaded. Check: journalctl -u crowdsec --since '1m ago'"
fi

echo ""
ok "Done. Watch for hits with:"
echo "    cscli alerts list --scenario Guezli/postfix-sasl-bf --since 24h"
